on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '.github/workflows/go-generate.yml'
      - 'template.go'
      - '*.go.tmpl'
name: go-generate
jobs:
  go-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
          (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)